language: node_js
node_js:
  - "10"

addons:
  chrome: stable

deploy:
  provider: heroku
  app: dropwizard-healthcheck-dash
  api_key:
    secure: bs49WfJUpMlldfJKUhn/vtJZ2lxENXL7WaS8SXu93NVP9vc0SuHUspPPtkDP+WW0efdsnmPAZ2OsHUuQVux5JNS4KIaL6dSTGQN/0fvF+pTepyNS0MyqfoPxxoaCTf6OlDVaEKIACti3WMfMI2pnL7uAa/VZaeE7ZyJ1USFPEO6i+dCfvsGGWoweQmSzlhBV9kW5beqjiBwcgeI4MVspd7rzV/6/J8kzzwHQ5oJFlzKzDoatzcmjepWUVyWS3JU4thh9EvUp9/ULCRDnRpmWQXlNALa2mFSJD06qY1XDtlu4GDSkL/UrbmS9MmmFdVe2UYGyCTN4uRX/8RrqX3nB1a4EQCTP5HcoUbEdc+m/gxYavzd4ctou9nD2p4iTSSioXGhLcO4Z14M2Ors12ZJh804dPO8daJqyD7CsvRAl10ZmNvWONsczIdosdZjG3yjZwWMttpqXed/jLYYasMnbmqxpOg6TSPQLNkXAqUAEhSVluJOAkcDQGDBUH2x91Hb+4eS3AHYOOf/a9fYY8i2EzeWm5FhQS3FmWEUj2j4h143/FbFPotDbSm/0vTBB1pZda6atWYeZaE07/ubLbUE3Xek0DQfDo98odogPO20pop3QUtIicJR4NObM07fOgANYS0Pr+UbNh17URenrAuhc9IUnmN9hNSskNEy5clZ61lg=
